Corrected testcases of the required config analysis, and more accurate circular detection(Bug 499534)
Change-Id: I702a8dc0479d8e6c05c6b5425dc2199901373f87
Signed-off-by: ebensza <bence.janos.szabo@ericsson.com>

diff --git a/regression_test/compileonly/mfgen-tpd/required_config/18/Makefile b/regression_test/compileonly/mfgen-tpd/required_config/18/Makefile
--- a/regression_test/compileonly/mfgen-tpd/required_config/18/Makefile
+++ b/regression_test/compileonly/mfgen-tpd/required_config/18/Makefile
@@ -29,21 +29,27 @@ endif
 #            c    |b:1
 #    c:1=>d:1|    |
 #            d>--->
-#Result will be: Error
+#Result will be: a:Default, b:Default, c:1, d:1
 MAKEPROG := ${MAKE}
 
 all: CheckTpd 
 
 BuildTpd:
-	$(TTCN3_DIR)/bin/ttcn3_makefilegen -f $(MFGEN_FLAGS) $(COVERAGE_FLAG) \
-	-t a.tpd -r -c -W -g 2>&1 | tee output
+	$(TTCN3_DIR)/bin/ttcn3_makefilegen -F $(MFGEN_FLAGS) $(COVERAGE_FLAG) \
+	-t a.tpd -r -c -W -g
 
 CheckTpd: BuildTpd
-	if [ `grep -c "error: Required configuration is inconsistent : Project 'b' cannot have 2 different configuration 'Default' and '1'" ./output` -ne 1 ]; \
-	then echo "Makefilegen required config test 18 failed: Overall verdict: fail" && exit 1; fi
+	if [ `grep -c "EXECUTABLE = binDefault" ./a_binDefault/Makefile` -ne 1 ]; \
+	then echo "Makefilegen required config test 52 failed: Overall verdict: fail" && exit 1; fi
+	if [ `grep -c "EXECUTABLE = binDefault" ./b_binDefault/Makefile` -ne 1 ]; \
+	then echo "Makefilegen required config test 52 failed: Overall verdict: fail" && exit 1; fi
+	if [ `grep -c "EXECUTABLE = bin1" ./c_bin1/Makefile` -ne 1 ]; \
+	then echo "Makefilegen required config test 52 failed: Overall verdict: fail" && exit 1; fi
+	if [ `grep -c "EXECUTABLE = bin1" ./d_bin1/Makefile` -ne 1 ]; \
+	then echo "Makefilegen required config test 52 failed: Overall verdict: fail" && exit 1; fi
 
 clean:
-	-rm -rf output a_binDefault
+	-rm -rf a_binDefault b_binDefault c_bin1 d_bin1
 
 distclean: clean
 	-rm -f *.out
diff --git a/regression_test/compileonly/mfgen-tpd/required_config/53/Makefile b/regression_test/compileonly/mfgen-tpd/required_config/53/Makefile
--- a/regression_test/compileonly/mfgen-tpd/required_config/53/Makefile
+++ b/regression_test/compileonly/mfgen-tpd/required_config/53/Makefile
@@ -39,15 +39,23 @@ MAKEPROG := ${MAKE}
 all: CheckTpd 
 
 BuildTpd:
-	$(TTCN3_DIR)/bin/ttcn3_makefilegen -f $(MFGEN_FLAGS) $(COVERAGE_FLAG) \
-	-t a.tpd -r -c -W -g 2>&1 | tee output
+	$(TTCN3_DIR)/bin/ttcn3_makefilegen -F $(MFGEN_FLAGS) $(COVERAGE_FLAG) \
+	-t a.tpd -r -c -W -g
 
 CheckTpd: BuildTpd
-	if [ `grep -c " error: Required configuration is inconsistent : Project 'e' cannot have 2 different configuration 'Default' and '1'" ./output` -ne 1 ]; \
-	then echo "Makefilegen required config test 53 failed: Overall verdict: fail" && exit 1; fi
+	if [ `grep -c "EXECUTABLE = binDefault" ./a_binDefault/Makefile` -ne 1 ]; \
+	then echo "Makefilegen required config test 54 failed: Overall verdict: fail" && exit 1; fi
+	if [ `grep -c "EXECUTABLE = binDefault" ./b_binDefault/Makefile` -ne 1 ]; \
+	then echo "Makefilegen required config test 54 failed: Overall verdict: fail" && exit 1; fi
+	if [ `grep -c "EXECUTABLE = bin1" ./c_bin1/Makefile` -ne 1 ]; \
+	then echo "Makefilegen required config test 54 failed: Overall verdict: fail" && exit 1; fi
+	if [ `grep -c "EXECUTABLE = binDefault" ./d_binDefault/Makefile` -ne 1 ]; \
+	then echo "Makefilegen required config test 54 failed: Overall verdict: fail" && exit 1; fi
+	if [ `grep -c "EXECUTABLE = bin1" ./e_bin1/Makefile` -ne 1 ]; \
+	then echo "Makefilegen required config test 54 failed: Overall verdict: fail" && exit 1; fi
 
 clean:
-	-rm -rf a_binDefault b_binDefault c_binDefault d_binDefault output
+	-rm -rf a_binDefault b_binDefault c_bin1 d_binDefault e_bin1
 
 distclean: clean
 	-rm -f *.out
